GET http://localhost:3000/api/autores

###

POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre": "Mario",
    "email": "Mario@gmail.com",
    "imagen": "https://s03.s3c.es/imag/_v0/1200x665/0/3/3/1200x655_mario-vaquerizo-monja-otraa1200.jpg"
}

### POSTS

GET http://localhost:3000/api/posts

###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "titulo": "NodeJS + Express",
    "descripcion": "Mario nos enseña a programar una API con Node y Express",
    "categoria": "programación",
    "autores_idautores": 6
}

###

GET http://localhost:3000/api/posts/autor/1